[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
